import { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app.vue",
    "./components/**/*.{vue,js,ts}",
    "./pages/**/*.{vue,js,ts}",
    "./layouts/**/*.{vue,js,ts}",
    "./plugins/**/*.{js,ts}",
    "./src/**/*.{vue,js,ts}",
  ],
  theme: {
    extend: {
      fontFamily: {
        hunter: ['MN HUNTER', 'sans-serif'],
        futura: ['Futura-REGULAR', 'sans-serif'],
      },
      container: {
        center: true,
        screens: {
          sm: "640px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1430px",
        },
      },
      padding: {
        "1": "1px",
        "2": "2px",
        "3": "3px",
        "4": "4px",
        "5": "5px",
        "6": "6px",
        "7": "7px",
        "8": "8px",
        "9": "9px",
        "10": "10px",
        "11": "11px",
        "12": "12px",
        "13": "13px",
        "14": "14px",
        "15": "15px",
        "16": "16px",
        "17": "17px",
        "18": "18px",
        "19": "19px",
        "20": "20px",
        "21": "21px",
        "22": "22px",
        "23": "23px",
        "24": "24px",
        "25": "25px",
        "26": "26px",
        "27": "27px",
        "28": "28px",
        "29": "29px",
        "30": "30px",
        "31": "31px",
        "32": "32px",
        "33": "33px",
        "34": "34px",
        "35": "35px",
        "36": "36px",
        "37": "37px",
        "38": "38px",
        "39": "39px",
        "40": "40px",
      },
      colors: {
        primary: "#ff3D00",
        secondary: "#134EA0",
        dark: "#212026",
        light: "#FFFFFF",
        black: "#000000",
        error: "#ed4e4e",
        danger: "#e71a3c",
        redDark: "#c52322",
        redLight: "#ff0000",
        success: "#18b460",
        grayLight: "#979393",
        blueDark: "#134ea0",
        blueLight: "#2972e7",
        hoverBlue: "#0056b3",
        orange: {
          DEFAULT: "#FF3300",
          light: "#FF6633",
          dark: "#CC2900",
        },
        background: {
          DEFAULT: "#EFEFEF",
          grayDark: "#EFEFEF",
          light: "#F9F9F9",
          primary: "#ff3D00",
          secondary: "#134EA0",
          dark: "#212026",
          white: "#FFFFFF",
          black: "#000000",
          error: "#ed4e4e",
          danger: "#e71a3c",
          redDark: "#c52322",
          redLight: "#ff0000",
          success: "#18b460",
          grayLight: "#979393",
          blueDark: "#134ea0",
          blueLight: "#2972e7",
        },
      },
      fontSize: {
        "1": "1px",
        "2": "2px",
        "3": "3px",
        "4": "4px",
        "5": "5px",
        "6": "6px",
        "7": "7px",
        "8": "8px",
        "9": "9px",
        "10": "10px",
        "11": "11px",
        "12": "12px",
        "13": "13px",
        "14": "14px",
        "15": "15px",
        "16": "16px",
        "17": "17px",
        "18": "18px",
        "19": "19px",
        "20": "20px",
        "21": "21px",
        "22": "22px",
        "23": "23px",
        "24": "24px",
        "25": "25px",
        "26": "26px",
        "27": "27px",
        "28": "28px",
        "29": "29px",
        "30": "30px",
        "31": "31px",
        "32": "32px",
        "33": "33px",
        "34": "34px",
        "35": "35px",
        "36": "36px",
        "37": "37px",
        "38": "38px",
        "39": "39px",
        "40": "40px",
      },
      keyframes: {
        "slide-in-right": {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)", opacity: "1" },
          "100%": { transform: "translateX(100%)", opacity: "0" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-out-left": {
          "0%": { transform: "translateX(0)", opacity: "1" },
          "100%": { transform: "translateX(-100%)", opacity: "0" },
        },
        "slide-down": {
          "0%": { transform: "translateY(-10%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-up": {
          "0%": { transform: "translateY(0)", opacity: "1" },
          "100%": { transform: "translateY(-10%)", opacity: "0" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-out-left": "slide-out-left 0.3s ease-in forwards",
        "slide-in-left": "slide-in-left 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-in forwards",
        "slide-down": "slide-down 0.25s ease-out",
        "slide-up": "slide-up 0.25s ease-in forwards",
      },
      safelist: [
        "animate-slide-in-right",
        "animate-slide-out-right",
        "animate-slide-in-left",
        "animate-slide-out-left",
      ],
    },
  },
  plugins: [],
};

export default config;
