export const MAIN_MENU = [
  {
    title: "VỀ BITI'S",
    link: "/ve-bitis",
  },
  {
    title: "NHÃN HIỆU",
    link: "/nhan-hieu",
    children: [
      { title: "BITI'S HUNTER", link: "/nhan-hieu/bitis-hunter" },
      { title: "GOSTO", link: "/nhan-hieu/gosto" },
      { title: "ÊMBRACE", link: "/nhan-hieu/embrace" },
      { title: "HELIO BY BITIS", link: "/nhan-hieu/helio" },
    ],
  },
  {
    title: "NAM",
    link: "/nam",
    children: [
      { title: "Hunter", link: "/nam/hunter" },
      { title: "Sandal", link: "/nam/sandal" },
      { title: "Giày Thể Thao", link: "/nam/the-thao" },
      { title: "Giày Chạy Bộ & Đi Bộ", link: "/nam/chay-bo" },
      { title: "Giày Tây", link: "/nam/tay" },
      { title: "Dép - Hài", link: "/nam/dep" },
      { title: "Balo", link: "/nam/balo" },
      { title: "Quần Áo", link: "/nam/quan-ao" },
    ],
  },
  {
    title: "NỮ",
    link: "/nu",
    children: [
      { title: "Hunter", link: "/nu/hunter" },
      { title: "Sandal", link: "/nu/sandal" },
      { title: "Giày Thể Thao", link: "/nu/the-thao" },
      { title: "Giày Cao Gót", link: "/nu/cao-got" },
      { title: "Giày Búp Bê", link: "/nu/bup-be" },
      { title: "Dép - Hài", link: "/nu/dep" },
      { title: "Túi Xách - Ví", link: "/nu/tui-xach" },
      { title: "Balo", link: "/nu/balo" },
      { title: "Quần Áo", link: "/nu/quan-ao" },
    ],
  },
  {
    title: "TEEN NAM",
    link: "/teen-nam",
    children: [
      { title: "Giày Thể Thao", link: "/teen-nam/the-thao" },
      { title: "Sandal", link: "/teen-nam/sandal" },
    ],
  },
  {
    title: "TEEN NỮ",
    link: "/teen-nu",
    children: [
      { title: "Giày Thể Thao", link: "/teen-nu/the-thao" },
      { title: "Sandal", link: "/teen-nu/sandal" },
    ],
  },
  {
    title: "BÉ TRAI",
    link: "/be-trai",
    children: [
      { title: "Giày Thể Thao", link: "/be-trai/giay-the-thao" },
      { title: "Sandal", link: "/be-trai/sandal" },
      { title: "Dép", link: "/be-trai/dep" },
      { title: "Giày & Sandal Tập Đi", link: "/be-trai/giay-sandal-tap-di" },
    ],
  },
  {
    title: "BÉ GÁI",
    link: "/be-gai",
    children: [
      { title: "Giày Thể Thao", link: "/be-gai/giay-the-thao" },
      { title: "Sandal", link: "/be-gai/sandal" },
      { title: "Dép Bé Gái", link: "/be-gai/dep" },
      { title: "Giày & Sandal Tập Đi", link: "/be-gai/giay-sandal-tap-di" },
      { title: "Giày Búp Bê", link: "/be-gai/bup-be" },
    ],
  },
  {
    title: "PHỤ KIỆN",
    link: "/phu-kien",
    children: [
      { title: "Balo", link: "/phu-kien/balo" },
      { title: "Balo Trẻ Em", link: "/phu-kien/balo-tre-em" },
      { title: "Túi Trẻ Em", link: "/phu-kien/tui-tre-em" },
      { title: "Túi Người Lớn", link: "/phu-kien/tui-nguoi-lon" },
      { title: "Ví", link: "/phu-kien/vi" },
      { title: "Vớ Người Lớn", link: "/phu-kien/vo-nguoi-lon" },
      { title: "Vớ Trẻ Em", link: "/phu-kien/vo-tre-em" },
      { title: "Áo Thun & Áo Khoác", link: "/phu-kien/ao-thun-ao-khoac" },
      { title: "Quần Dài & Quần Short", link: "/phu-kien/quan-dai-quan-short" },
      { title: "Nón", link: "/phu-kien/non" },
      { title: "Charm", link: "/phu-kien/charm" },
      { title: "Lót Đế", link: "/phu-kien/lot-de" },
      { title: "Dây Giày", link: "/phu-kien/day-giay" },
      { title: "Gấu Bông", link: "/phu-kien/gau-bong" },
      { title: "Xịt Khử Mùi", link: "/phu-kien/xit-khu-mui" },
    ],
  },
  {
    title: "CHIA SẺ",
    link: "/chia-se",
    children: [
      { title: "Xu Hướng Thời Trang", link: "/chia-se/xu-huong-thoi-trang" },
      { title: "Tư Vấn Chọn Size", link: "/chia-se/tu-van-chon-size" },
      { title: "Kinh Nghiệm Hay", link: "/chia-se/kinh-nghiem-hay" },
    ],
  },
];
